export const seedData = {
  profile: {
    name: "Piyush Ghonge",
    title: "Computer Science Engineering Undergraduate",
    subtitle: "Full-Stack Developer / Software Development Enthusiast",
    tagline:
      "Computer Science Engineering undergraduate focused on building practical software solutions, exploring full-stack development, and continuously improving through real-world projects.",
    email: "pranayghonge2006@gmail.com",
    phone: "+918788517046",
    location: "Ballarpur, Maharashtra, India",
    photo: "",
  },
  about: {
    content:
      "I'm a 3rd-year Computer Science Engineering undergraduate at P. R. Pote Patil College of Engineering and Management, passionate about software development and building practical solutions. I'm actively learning full-stack development, working with modern technologies, and developing real-world projects that solve actual problems.\n\nI believe in continuous learning and hands-on experience. Every project I build teaches me something new about software engineering, problem-solving, and teamwork. I'm currently focused on strengthening my full-stack development skills while exploring new technologies and preparing for professional opportunities.",
  },
  settings: {
    siteTitle: "Piyush Ghonge",
    tagline: "Computer Science Engineering Student & Developer",
    email: "pranayghonge2006@gmail.com",
    phone: "+918788517046",
    location: "Ballarpur, Maharashtra, India",
    footerText: "",
    defaultTheme: "dark",
  },
  socials: [
    { platform: "github", url: "https://github.com/PiyushGhonge2006", order: 0 },
    { platform: "linkedin", url: "https://www.linkedin.com/in/piyush-ghonge-859961358", order: 1 },
    { platform: "instagram", url: "", order: 2 },
    { platform: "youtube", url: "", order: 3 },
  ],
  education: [
    {
      degree: "Bachelor of Engineering",
      field: "Computer Science Engineering",
      institution: "P. R. Pote Patil College of Engineering and Management",
      period: "2024 - 2028",
      grade: "CGPA: 8.5",
      description:
        "Currently in 3rd year, focusing on software development, data structures, algorithms, and full-stack web development.",
      order: 0,
    },
    {
      degree: "12th (Science)",
      field: "Science",
      institution: "Guru Nanak Public H/S School",
      period: "2022 - 2024",
      grade: "87.67%",
      description: "State Board, Ballarpur, Maharashtra.",
      order: 1,
    },
    {
      degree: "10th",
      field: "",
      institution: "Mount English Medium School",
      period: "2022",
      grade: "89.80%",
      description: "State Board, Ballarpur, Maharashtra.",
      order: 2,
    },
  ],
  skills: [
    { category: "Programming Languages", name: "C", order: 0 },
    { category: "Programming Languages", name: "C++", order: 1 },
    { category: "Programming Languages", name: "Java", order: 2 },
    { category: "Programming Languages", name: "Python", order: 3 },
    { category: "Programming Languages", name: "JavaScript", order: 4 },
    { category: "Databases", name: "SQL", order: 0 },
    { category: "Databases", name: "MongoDB", order: 1 },
    { category: "Databases", name: "MySQL", order: 2 },
    { category: "Frameworks & Libraries", name: "React", order: 0 },
    { category: "Frameworks & Libraries", name: "Node.js", order: 1 },
    { category: "Frameworks & Libraries", name: "Express.js", order: 2 },
    { category: "Frameworks & Libraries", name: "Tailwind CSS", order: 3 },
    { category: "Tools & Platforms", name: "VS Code", order: 0 },
    { category: "Tools & Platforms", name: "GitHub", order: 1 },
    { category: "Tools & Platforms", name: "GitHub Actions", order: 2 },
    { category: "Tools & Platforms", name: "Vite", order: 3 },
    { category: "Soft Skills", name: "Communication", order: 0 },
    { category: "Soft Skills", name: "Teamwork", order: 1 },
    { category: "Soft Skills", name: "Problem Solving", order: 2 },
    { category: "Soft Skills", name: "Time Management", order: 3 },
    { category: "Soft Skills", name: "Leadership", order: 4 },
  ],
  experience: [
    {
      organization: "Eduskill",
      position: "Intern",
      mode: "Remote",
      location: "Maharashtra, India",
      startDate: "2025",
      endDate: "Present",
      description:
        "Worked on learning and applying various technologies including Weather API, Traffic API, and IoT Sensor integration.",
      technologies: ["C", "C++", "Java", "Python", "HTML", "CSS", "JavaScript", "React"],
      order: 0,
    },
  ],
  projects: [
    {
      name: "Preorder Canteen App",
      shortDescription:
        "Full-stack web application enabling students to pre-order food from a college canteen, helping reduce waiting time and improve order management.",
      detailedDescription:
        "A complete full-stack solution featuring user authentication, menu management, order tracking, and administrative functionality. Built with modern technologies following REST API architecture and client-server design patterns.",
      technologies: [
        "React",
        "Vite",
        "JavaScript",
        "React Router DOM",
        "Tailwind CSS",
        "Radix UI",
        "Lucide React",
        "Node.js",
        "Express.js",
        "MongoDB",
        "Mongoose",
        "JWT",
        "bcrypt.js",
        "REST APIs",
        "Axios",
      ],
      features: [
        "Responsive UI",
        "User Authentication",
        "Menu Management",
        "Order Tracking",
        "Administrative Functionality",
        "REST APIs",
        "Client-Server Architecture",
        "Git/GitHub Version Control",
      ],
      status: "Ongoing",
      github: "",
      liveDemo: "",
      image: "",
      screenshots: [],
      featured: true,
      sortOrder: 0,
    },
    {
      name: "Supply Chain",
      shortDescription: "A Supply Chain application focused on improving operational efficiency.",
      detailedDescription:
        "A comprehensive supply chain management application built with the MERN stack, designed to streamline and optimize supply chain operations.",
      technologies: ["React", "Vite", "Tailwind CSS", "JavaScript", "Node.js", "Express.js", "MongoDB Atlas"],
      features: ["Operational Efficiency", "Supply Chain Management"],
      status: "Ongoing",
      github: "",
      liveDemo: "",
      image: "",
      screenshots: [],
      featured: true,
      sortOrder: 1,
    },
    {
      name: "Voice Control PC",
      shortDescription:
        "Voice-controlled PC assistant using Python and speech recognition to execute desktop commands, launch applications, browse the web, and automate everyday tasks through voice input.",
      detailedDescription:
        "A Python-based voice assistant that leverages speech recognition to perform desktop operations, application launching, web browsing, and task automation through natural voice commands.",
      technologies: ["Python"],
      features: ["Voice Recognition", "Desktop Commands", "Application Launching", "Web Browsing", "Task Automation"],
      status: "Ongoing",
      github: "",
      liveDemo: "",
      image: "",
      screenshots: [],
      featured: true,
      sortOrder: 2,
    },
    {
      name: "Rock Paper Scissors Game",
      shortDescription:
        "Interactive Rock Paper Scissors browser game with real-time user interactions, game logic and DOM manipulation.",
      detailedDescription:
        "A fun and interactive browser-based Rock Paper Scissors game featuring real-time gameplay, smooth animations, and dynamic DOM manipulation.",
      technologies: ["HTML", "CSS", "JavaScript"],
      features: ["Real-time Gameplay", "DOM Manipulation", "Responsive Design"],
      status: "Completed",
      startDate: "June 2026",
      github: "",
      liveDemo: "",
      image: "",
      screenshots: [],
      featured: false,
      sortOrder: 3,
    },
    {
      name: "Amazon Clone",
      shortDescription:
        "Static Amazon-inspired website interface built using HTML5 and CSS3.",
      detailedDescription:
        "A static Amazon-inspired website interface showcasing front-end development skills with clean HTML5 and CSS3 implementation. Currently being improved with responsive design.",
      technologies: ["HTML", "CSS"],
      features: ["Static Interface", "HTML5", "CSS3", "Responsive Design (In Progress)"],
      status: "In Progress",
      startDate: "January 2026",
      github: "",
      liveDemo: "",
      image: "",
      screenshots: [],
      featured: false,
      sortOrder: 4,
    },
  ],
  certificates: [
    { title: "C++ Language Certificate", issuer: "", date: "", credentialId: "", image: "", pdf: "", url: "", featured: false },
    { title: "Java (Including Graphics) Language Certificate", issuer: "", date: "", credentialId: "", image: "", pdf: "", url: "", featured: false },
    { title: "Community Engagement Project Exhibition Certificate", issuer: "", date: "", credentialId: "", image: "", pdf: "", url: "", featured: false },
    { title: "Drone Workshop Certificate", issuer: "", date: "", credentialId: "", image: "", pdf: "", url: "", featured: false },
    { title: "B10x Certificate", issuer: "", date: "", credentialId: "", image: "", pdf: "", url: "", featured: false },
    { title: "Eduskill Course Certificate", issuer: "Eduskill", date: "", credentialId: "", image: "", pdf: "", url: "", featured: false },
  ],
  achievements: [
    {
      title: "Winner of Communicative Engagement Project (CEP)",
      description: "Secured 1st Rank in the Computer Science Department project exhibition.",
      organization: "Computer Science Department",
      date: "September 2025",
      rank: "1st Rank",
      image: "",
      link: "",
      featured: true,
    },
  ],
}