export const resourceConfigs = {
  projects: {
    title: 'Projects',
    endpoint: '/admin/projects',
    icon: 'FolderKanban',
    orderable: true,
    orderField: 'sortOrder',
    searchKeys: ['name', 'status', 'technologies'],
    list: { primary: 'name', secondary: 'status', badge: (p) => (p.featured ? 'Featured' : null) },
    fields: [
      { name: 'name', label: 'Project Name', type: 'text', required: true },
      { name: 'shortDescription', label: 'Short Description', type: 'textarea', rows: 3 },
      { name: 'detailedDescription', label: 'Detailed Description', type: 'textarea', rows: 5 },
      { name: 'category', label: 'Category', type: 'text', placeholder: 'Full-Stack, Frontend, etc.' },
      { name: 'status', label: 'Status', type: 'select', options: ['Ongoing', 'In Progress', 'Completed', 'Planned'] },
      { name: 'featured', label: 'Mark as Featured', type: 'checkbox' },
      { name: 'technologies', label: 'Technologies', type: 'tags' },
      { name: 'features', label: 'Features', type: 'tags' },
      { name: 'startDate', label: 'Start Date', type: 'text', placeholder: 'e.g. January 2026' },
      { name: 'endDate', label: 'End Date', type: 'text', placeholder: 'e.g. June 2026' },
      { name: 'github', label: 'GitHub URL', type: 'text', placeholder: 'https://github.com/...' },
      { name: 'liveDemo', label: 'Live Demo URL', type: 'text', placeholder: 'https://...' },
      { name: 'image', label: 'Main Image', type: 'upload' },
      { name: 'screenshots', label: 'Screenshots', type: 'gallery' },
      { name: 'sortOrder', label: 'Sort Order', type: 'number', helper: 'Lower numbers appear first' },
    ],
  },
  skills: {
    title: 'Skills',
    endpoint: '/admin/skills',
    icon: 'Code2',
    orderField: 'order',
    searchKeys: ['name', 'category'],
    list: { primary: 'name', secondary: 'category' },
    fields: [
      { name: 'name', label: 'Skill Name', type: 'text', required: true },
      {
        name: 'category',
        label: 'Category',
        type: 'text',
        required: true,
        placeholder: 'Programming Languages, Databases, Tools, Soft Skills, etc.',
      },
      { name: 'order', label: 'Order', type: 'number' },
    ],
  },
  education: {
    title: 'Education',
    endpoint: '/admin/education',
    icon: 'GraduationCap',
    orderField: 'order',
    searchKeys: ['degree', 'institution', 'period'],
    list: { primary: 'degree', secondary: 'institution' },
    fields: [
      { name: 'degree', label: 'Degree', type: 'text', required: true },
      { name: 'field', label: 'Field / Stream', type: 'text' },
      { name: 'institution', label: 'Institution', type: 'text' },
      { name: 'period', label: 'Period', type: 'text', placeholder: 'e.g. 2024 - 2028' },
      { name: 'grade', label: 'Grade / Percentage', type: 'text', placeholder: 'e.g. CGPA: 8.5' },
      { name: 'description', label: 'Description', type: 'textarea', rows: 3 },
      { name: 'order', label: 'Order', type: 'number' },
    ],
  },
  experience: {
    title: 'Experience',
    endpoint: '/admin/experience',
    icon: 'Briefcase',
    orderField: 'order',
    searchKeys: ['organization', 'position'],
    list: { primary: 'position', secondary: 'organization' },
    fields: [
      { name: 'organization', label: 'Organization', type: 'text', required: true },
      { name: 'position', label: 'Position', type: 'text', required: true },
      { name: 'mode', label: 'Work Mode', type: 'select', options: ['', 'Remote', 'On-site', 'Hybrid'] },
      { name: 'location', label: 'Location', type: 'text' },
      { name: 'startDate', label: 'Start Date', type: 'text', placeholder: 'e.g. 2025' },
      { name: 'endDate', label: 'End Date', type: 'text', placeholder: 'e.g. Present' },
      { name: 'description', label: 'Description', type: 'textarea', rows: 4 },
      { name: 'technologies', label: 'Technologies', type: 'tags' },
      { name: 'order', label: 'Order', type: 'number' },
    ],
  },
  certificates: {
    title: 'Certificates',
    endpoint: '/admin/certificates',
    icon: 'Award',
    searchKeys: ['title', 'issuer', 'date'],
    list: { primary: 'title', secondary: 'issuer', badge: (c) => (c.featured ? 'Featured' : null) },
    fields: [
      { name: 'title', label: 'Certificate Title', type: 'text', required: true },
      { name: 'issuer', label: 'Issuing Organization', type: 'text' },
      { name: 'date', label: 'Date', type: 'text', placeholder: 'e.g. March 2026' },
      { name: 'credentialId', label: 'Credential ID (optional)', type: 'text' },
      { name: 'featured', label: 'Mark as Featured', type: 'checkbox' },
      { name: 'image', label: 'Certificate Image', type: 'upload' },
      { name: 'pdf', label: 'Certificate PDF', type: 'upload', accept: 'application/pdf' },
      { name: 'url', label: 'Certificate URL', type: 'text', placeholder: 'https://...' },
    ],
  },
  achievements: {
    title: 'Achievements',
    endpoint: '/admin/achievements',
    icon: 'Trophy',
    searchKeys: ['title', 'organization', 'rank'],
    list: { primary: 'title', secondary: 'organization', badge: (a) => (a.featured ? 'Featured' : null) },
    fields: [
      { name: 'title', label: 'Achievement Title', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea', rows: 3 },
      { name: 'organization', label: 'Organization', type: 'text' },
      { name: 'date', label: 'Date', type: 'text', placeholder: 'e.g. September 2025' },
      { name: 'rank', label: 'Rank / Result', type: 'text', placeholder: 'e.g. 1st Rank' },
      { name: 'featured', label: 'Mark as Featured', type: 'checkbox' },
      { name: 'image', label: 'Image', type: 'upload' },
      { name: 'link', label: 'External Link', type: 'text', placeholder: 'https://...' },
    ],
  },
  socials: {
    title: 'Social Links',
    endpoint: '/admin/socials',
    icon: 'Share2',
    searchKeys: ['platform', 'url'],
    list: { primary: 'platform', secondary: 'url' },
    fields: [
      {
        name: 'platform',
        label: 'Platform',
        type: 'select',
        options: ['github', 'linkedin', 'instagram', 'youtube'],
        required: true,
      },
      { name: 'url', label: 'URL (empty = hidden)', type: 'text', placeholder: 'https://...' },
      { name: 'order', label: 'Order', type: 'number' },
    ],
  },
}